#!/bin/bash
set -eux -o pipefail

# Adapted from `drake`s `install_prereqs.sh`.
cur=$(cd $(dirname ${BASH_SOURCE}) && pwd)

dpkg_install_from_wget() {
  package="$1"
  version="$2"
  url="$3"
  checksum="$4"

  # Skip the install if we're already at the exact version.
  installed=$(dpkg-query --showformat='${Version}\n' --show "${package}" 2>/dev/null || true)
  if [[ "${installed}" == "${version}" ]]; then
    echo "${package} is already at the desired version ${version}"
    return
  fi

  # Download and verify.
  tmpdeb="/tmp/${package}_${version}-amd64.deb"
  wget -O "${tmpdeb}" "${url}"
  if echo "${checksum} ${tmpdeb}" | sha256sum -c -; then
    echo  # Blank line between checkout output and dpkg output.
  else
    echo "The ${package} deb does not have the expected SHA256. Not installing." >&2
    exit 2
  fi

  # Install.
  dpkg -i "${tmpdeb}"
  rm "${tmpdeb}"
}

apt-get update

# Ensure we can fetch things and check our system.
apt-get install --no-install-recommends $(cat <<EOF
  ca-certificates
  lsb-release
  wget
EOF
)

# Install bazel package dependencies (these may duplicate dependencies of
# drake).
apt-get install --no-install-recommends $(cat <<EOF
g++
unzip
zlib1g-dev
EOF
)

# Install bazel.
dpkg_install_from_wget \
  bazel 4.0.0 \
  https://releases.bazel.build/4.0.0/release/bazel_4.0.0-linux-x86_64.deb \
  1779ce76ebf449e55dfdd1318355335179eb85609042dfe5c1b4b34683dfd4b5

apt-get install --no-install-recommends lsb-release

codename=$(lsb_release -sc)

# Ensure we can use vanilla Python 3's pip.
# Install Python 2 because Bazel's wrapper script tends to use `python`?
# TODO(eric.cousineau): Yuck! Fix this?
if [[ ${codename} == "bionic" ]]; then
  apt-get install --no-install-recommends $(cat <<EOF
libpython-stdlib
python-minimal
python3-pip
EOF
)
else
  apt-get install --no-install-recommends $(cat <<EOF
libpython2-stdlib
python-is-python2
python2-minimal
python3-pip
EOF
)
fi

# Ensure we can use `sudo`. (See notes in `test.sh`).
apt-get install --no-install-recommends $(cat <<EOF
sudo
EOF
)
