workspace(name = "external_data_pkg_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.2/rules_python-0.0.2.tar.gz",
    strip_prefix = "rules_python-0.0.2",
    sha256 = "b5668cde8bb6e3515057ef465a35ad712214962f0b3a314e551204266c7be90c",
)

register_toolchains("//:py_toolchain")

load("//:drake_path.bzl", "get_drake_path")

local_repository(
    name = "bazel_external_data_pkg",
    path = get_drake_path(__workspace_dir__),
)

load("//:repo_example.bzl", "add_repo_archive_repository")

add_repo_archive_repository()
