#!/bin/bash
set -e -u

# Proxy to use Bazel binary, but access to PWD.

workspace_dir=$(cd $(dirname $0)/.. && pwd)
bin_dir=${workspace_dir}/bazel-bin/external/bazel_external_data_pkg
bin=${bin_dir}/cli

cli_extra_args=--user_config=${workspace_dir}/tools/external_data.user.yml

do_build=
if [[ $# -gt 0 && $1 == --do_build ]]; then
    do_build=1
    shift
fi

if [[ ! -f ${bin} || -n $do_build ]]; then
    # TODO(eric.cousineau): Is there a way to use the previous build config,
    # so that Bazel doesn't switch the symlink and possibly lose whatever
    # other artifacts the user may want???
    bazel build @bazel_external_data_pkg//:cli
fi

echo "cmd: ${bin} ${cli_extra_args} $@" | \
    sed \
        -e "s#${bin_dir}#\${bin_dir}#g" \
        -e "s#${workspace_dir}#\${workspace_dir}#g"
${bin} ${cli_extra_args} "$@"
