name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  ubuntu_focal:
    name: ubuntu 20.04 focal
    runs-on: ubuntu-latest
    container: ubuntu:focal
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: ./setup/ci/common/install_prereqs.sh
        shell: bash
      - name: test
        run: ./setup/ci/common/test.sh
        shell: bash
